language: go

go:
  - 1.6

before_install:
  # @see https://github.com/travis-ci/travis-ci/issues/4264
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y remove --purge postgresql-9.1
  - sudo apt-get -y remove --purge postgresql-9.2
  - sudo apt-get -y remove --purge postgresql-9.3
  - sudo apt-get -y remove --purge postgresql-9.4
  - sudo apt-get -y autoremove
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-9.5
  - sudo sh -c 'echo "local all all trust" > /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo /etc/init.d/postgresql restart

before_script:
  - psql -c "CREATE USER rentmycourt ENCRYPTED PASSWORD 'rentmycourt';" -U postgres
  - psql -c 'CREATE DATABASE rentmycourt OWNER=rentmycourt;' -U postgres

install:
  - go get
  - go get github.com/golang/lint/golint

branches:
  only:
    - master

script:
  - make
  - golint --set_exit_status ./...
